
#ifndef __COMMON_H
#define __COMMON_H

#define __RT_ENABLE_SPECULAR_OPERATIONS
#define __RT_ENABLE_RECURSIVE_REFLECT
#define __RT_ENABLE_RECURSIVE_REFRACT
#define __RT_ENABLE_SHADOWS_OPERATIONS

#define	RT_EPSILON	0.00001f
#define RT_INFINITE	10000.0f

#endif
